dependencies {
    implementation("com.microsoft.azure:azure-toolkit-auth-lib")
    implementation("com.microsoft.azure:azure-toolkit-ide-common-lib")
    implementation(project(":azure-intellij-plugin-lib"))
    // runtimeOnly project(path: ":azure-intellij-plugin-lib", configuration: "instrumentedJar")
    implementation(project(":azure-intellij-plugin-lib-java"))
    // runtimeOnly project(path: ":azure-intellij-plugin-lib-java", configuration: "instrumentedJar")
    implementation(project(":azure-intellij-plugin-appservice"))
    // runtimeOnly project(path: ":azure-intellij-plugin-appservice", configuration: "instrumentedJar")
    implementation(project(":azure-intellij-plugin-guidance"))
    // runtimeOnly project(path: ":azure-intellij-plugin-guidance", configuration: "instrumentedJar")
    implementation(project(":azure-intellij-plugin-guidance-java"))
    // runtimeOnly project(path: ":azure-intellij-plugin-guidance-java", configuration: "instrumentedJar")
    implementation(project(":azure-intellij-plugin-storage"))
    // runtimeOnly project(path: ":azure-intellij-plugin-storage", configuration: "instrumentedJar")
    implementation(project(":azure-intellij-resource-connector-lib"))
    // runtimeOnly project(path: ":azure-intellij-resource-connector-lib", configuration: "instrumentedJar")
    implementation(project(":azure-intellij-plugin-containerregistry"))
    // runtimeOnly project(path: ":azure-intellij-plugin-containerregistry", configuration: "instrumentedJar")
    implementation(project(":azure-intellij-plugin-containerapps"))
    // runtimeOnly project(path: ":azure-intellij-plugin-containerapps", configuration: "instrumentedJar")
    implementation("com.github.docker-java:docker-java:3.3.0")
    implementation("com.microsoft.azure:azure-toolkit-appservice-lib")
    implementation("com.microsoft.azure:azure-toolkit-ide-appservice-lib")
    implementation("com.microsoft.azure:azure-toolkit-ide-containerapps-lib")
    implementation("com.microsoft.azure:azure-toolkit-ide-containerregistry-lib")
    implementation("com.jcraft:jsch:0.1.55")
    implementation("org.codehaus.plexus:plexus-archiver:4.2.7")
    implementation("org.codehaus.plexus:plexus-container-default:2.1.1")
    implementation("com.neovisionaries:nv-websocket-client:2.14")

    intellijPlatform {
        // Plugin Dependencies. Uses `platformBundledPlugins` property from the gradle.properties file for bundled IntelliJ Platform plugins.
        bundledPlugin("com.intellij.java")
        bundledPlugin("org.jetbrains.idea.maven")
        bundledPlugin("org.jetbrains.idea.maven.model")
        bundledPlugin("org.jetbrains.idea.maven.server.api")
        bundledPlugin("com.intellij.gradle")
        bundledPlugin("org.jetbrains.plugins.gradle")
    }
}