#!/usr/bin/env sh

# Copyright (c) 2020 JetBrains s.r.o.
# <p/>
# All rights reserved.
# <p/>
# MIT License
# <p/>
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
# documentation files (the "Software"), to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and
# to permit persons to whom the Software is furnished to do so, subject to the following conditions:
# <p/>
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of
# the Software.
# <p/>
# THE SOFTWARE IS PROVIDED *AS IS*, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO
# THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

#APP_ARGS=$(save "$@")
APP_BASE_NAME=`basename "$0"`

if [ $APP_BASE_NAME != "func" ]; then
    echo "[$APP_BASE_NAME] test tool should be named [func]"
    exit 1
fi

if [ "$1" != "--version" ]; then
    echo "[$APP_BASE_NAME] test tool must have single parameter: --version"
    exit 1
fi

echo "3.0.2009"
exit 0
